CONFIG_ZMK_USB_LOGGING=n

# name of Bluetooth device (up to 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="Sph's Totem"

# enables mouse
CONFIG_ZMK_POINTING=y

# enables f13-f24 to report current state to waybar, but blocks android support
# CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
# CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y
# CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
# CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# CONFIG_ZMK_SETTINGS_RESET_ON_START=y # uncomment one time after changing name to apply it
